platform :ios, '15.0'

target 'App' do
  use_frameworks!
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Отключаем встраивание фреймворков через Pods
      config.build_settings['SKIP_INSTALL'] = 'YES'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
      config.build_settings['SWIFT_ACTIVE_EXECUTION_ENVIRONMENT'] = 'NO'
    end
  end
  
  # Удаляем build phase который встраивает фреймворки
  installer.pods_project.targets.each do |target|
    if target.name == 'App'
      target.build_phases.each do |phase|
        if phase.respond_to?(:name) && phase.name.include?('Embed')
          phase.remove_from_project
        end
      end
    end
  end
end